name: Daily Stock Batch Ingestion

on:
  schedule:
    - cron: '0 3 * * *' # สั่งรันทุกตี 3 ของทุกวัน (เวลา UTC)
  workflow_dispatch: # ปุ่มกดรันเองด้วยมือ (เอาไว้ทดสอบ)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run Extraction Script
        env:
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }} # เก็บ Key ไว้ใน Secrets เพื่อความปลอดภัย
        run:  python scripts/extract_stock.py
